### PR TITLE
Expose a list of available formats

### PR DESCRIPTION
**Pull request by blink1073**
See #93.

### CODE REVIEW

**Comment by blink1073** [comment]
I'd also suggest mentioning this in the docstrings.

**Comment by almarklein** [comment]
With this, you don't get a nice list. Now I remember .... `print(imageio.formats)` gives you a nice list of all formats. But this is a bit awkward and not documented well.

What about a `show_fomats()` function that we can document and mention where we talk of formats?

**Comment by blink1073** [comment]
How is that?

**Comment by almarklein** [comment]
Oh crap, know your own package... `imageio.help()` did exactly that. But the fact that I forgot is telling that we need this PR :). 

Can you please add this function to the docs (userapi.rst) while you're in there?

**Comment by blink1073** [comment]
Done.

**Comment by almarklein** [comment]
appveyor timed out. LGTM.

**Comment by almarklein** [comment]
Thanks!

**Pull request merged**
