### PR TITLE
Make wheels

### LINKED ISSUE #91: Use Wheels on PyPI
Right now, `pip install imageio` downloads the Linux tarball and associated `freeimage` library.  Wheels are preferred downloads for pip.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #91.

```bash
$ ls dist
imageio-1.3-py2.py3-linux_i386.whl
imageio-1.3-py2.py3-linux_x86_64.whl
imageio-1.3-py2.py3-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
imageio-1.3-py2.py3-win32.whl
imageio-1.3-py2.py3-win_amd64.whl
```

### CODE REVIEW

**Comment by blink1073** [comment]
OSX is being irrationally difficult.  My 2 cents would be to include the OSX library in the tarball and provide the other wheels.

**Comment by blink1073** [comment]
I'm going to take a break from this: it is maddening.

**Comment by blink1073** [comment]
Apparently PyPI completely blocks Linux wheels at the moment...

**Comment by blink1073** [comment]
I'm calling this a dead end.

**Comment by almarklein** [comment]
Arg. Why is it so hard? Aren't many packages building and uploading wheels?

**Comment by almarklein** [comment]
"Why is it so hard" not meant as a personal thing, but more like why is setuptools/pypi not making this easy for us...

**Comment by blink1073** [comment]
Two examples:
https://pypi.python.org/pypi/pyzmq <https://pypi.python.org/pypi/pyzmq>
https://pypi.python.org/pypi/Pillow/2.9.0 <https://pypi.python.org/pypi/Pillow/2.9.0>

Both messy, neither one supports osx very well or Linux at all.


Regards,

Steve

* * * * * * *
Steven Silvester
Silvester Consulting, LLC
610 Maine Ave
Fort Walton Beach, FL 32547
steven.silvester@ieee.org <mailto:steven.silvester@ieee.org>
(850) 273-8276

**Comment by blink1073** [comment]
Okay, updated thoughts:
Release wheels for win64 and osx64 for py27 and py34 (I figured out the syntax).
Include the linux64 version in the tarball.
All other combinations would have to download.

**Comment by blink1073** [comment]
Note to self:
imageio-1.3-cp27-none-macosx_10_5_x86_64.whl
imageio-1.3-cp34-none-macosx_10_5_x86_64.whl
imageio-1.3-cp34-none-win_amd64.whl
imageio-1.3-cp27-none-win_amd64.whl

**Comment by blink1073** [comment]
Here's my dist directory after running `python setup.py sdist_all bdist_wheel_all`:

```bash
$ ll dist
total 95336
-rw-r--r--  1 ssilvester  staff  4766656 Jul  9 11:05 imageio-1.3-cp27-none-macosx_10_5_x86_64.whl
-rw-r--r--  1 ssilvester  staff  4434964 Jul  9 11:05 imageio-1.3-cp27-none-win_amd64.whl
-rw-r--r--  1 ssilvester  staff  4766656 Jul  9 11:05 imageio-1.3-cp34-none-macosx_10_5_x86_64.whl
-rw-r--r--  1 ssilvester  staff  4434964 Jul  9 11:05 imageio-1.3-cp34-none-win_amd64.whl
-rw-r--r--  1 ssilvester  staff  5043110 Jul  9 11:06 imageio-1.3-linux32.zip
-rw-r--r--  1 ssilvester  staff  5114168 Jul  9 11:06 imageio-1.3-linux64.zip
-rw-r--r--  1 ssilvester  staff  4820461 Jul  9 11:06 imageio-1.3-osx64.zip
-rw-r--r--  1 ssilvester  staff  3205861 Jul  9 11:04 imageio-1.3-py3-none-any.whl
-rw-r--r--  1 ssilvester  staff  4290741 Jul  9 11:06 imageio-1.3-win32.zip
-rw-r--r--  1 ssilvester  staff  4488877 Jul  9 11:06 imageio-1.3-win64.zip
-rw-r--r--  1 ssilvester  staff  3231393 Jul  9 11:06 imageio-1.3.tar.gz
-rw-r--r--  1 ssilvester  staff   199552 Jul  9 11:06 imageio-1.3.zip
```

**Comment by almarklein** [comment]
No wheels for Linux?

**Comment by almarklein** [comment]
And what about 32bit? If its a matter of adding a few lines to make that work, why not? Or is there a problem I am overlooking?

I'd like to get rid of the sdist_all option if wheels work ok enough.

**Comment by blink1073** [comment]
PyPI does not accept wheels, so the the minimum set you could get is:

win32 wheels
win64 wheels
linux32 tar
osx wheels
tar with linux64
source zip

My intent with the previous list was to only provide eggs for the most common cases, and
provide an escape hatch for everyone else.  For instance, win64 py33 users.

**Comment by almarklein** [comment]
But in our case the cp34 wheels are exactly the same as our cp33 wheels since the binaries are not bound to a specific Python version. Can we just copy+rename in these cases?

**Comment by blink1073** [comment]
Producing the wheels is not the problem, its just thriwing more build options together. Want me to add all possible valid combinations?



—

**Comment by almarklein** [comment]
What do you mean by build options? Can we not just have `bdist_wheel_all` produce wheels for all combinations? What I meant is that from `imageio-1.3-cp27-none-win_amd64.whl` we can easily create a wheel for any Python version. So basically you can create 4 wheels and then copy+rename them for all Python versions that we want to support.

Or is the python version also included as meta info inside the wheel?

**Comment by blink1073** [comment]
Ah, yes, that will work because when it builds we have the following created file:

```bash
Wheel-Version: 1.0
Generator: bdist_wheel (0.24.0)
Root-Is-Purelib: true
Tag: py2-none-any
Tag: py3-none-any
```

So it will grab the correct file based on name and install no matter what the underlying platform is.

**Comment by blink1073** [comment]
Here's what the Pillow files look like:

```
Pillow-2.9.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Pillow-2.9.0-cp34-none-win32.whl
Pillow-2.9.0-cp34-none-win_amd64.whl
```

**Comment by blink1073** [comment]
And for whatever reason the 2.7 Mac wheel is different:

`Pillow-2.9.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl`

**Comment by blink1073** [comment]
Let's bear in mind that `libfreeimage` is available on Homebrew, MacPorts, Debian, and soon Anaconda.  Are we fighting a battle that does not need to be be fought on Mac and Linux?

**Comment by matthew-brett** [comment]
I'm trying to build a wheel-building repo : 

https://github.com/MacPython/imageio-wheels

I can now build (on travis) a dual arch Freeimage dylib, that should work on OSX 10.6, as OSX wheels require.

But - where should I copy this dylib into the imageio directory tree in order to build the wheel?

I currently copy into the `imageio` directory, but should it go into `resources`?

**Comment by matthew-brett** [comment]
Building OK now, but lots of test errors: https://travis-ci.org/MacPython/imageio-wheels/builds/70906322

**Comment by blink1073** [comment]
Yes, we've been putting it in `resources`.

**Comment by almarklein** [comment]
`resources/freeimage` to be precise.

**Comment by almarklein** [comment]
@matthew-brett The failures are because it cannot download the test images that are needed. Is it an idea to put a subset of images in the wheel as well?  It's these files:
```python
    for fname in ['images/chelsea.png',
                  'images/chelsea.zip',
                  'images/astronaut.png',
                  'images/newtonscradle.gif',
                  'images/cockatoo.mp4',
                  'images/realshort.mp4',
                  'images/stent.npz',
                  ]:
        imageio.core.get_remote_file(fname, resource_dir, 
                                     force_download=True)
```

**Comment by matthew-brett** [comment]
Is that the desired behavior - to ship the images inside the wheel?

I guess you are planning that the user should be able to run the tests on their own installation?  So they should have the test images on their system too?

**Comment by blink1073** [comment]
I think it makes sense to have these included in the install, the same way we do currently with `skimage.data`.

**Comment by almarklein** [comment]
It also helps users to run basic examples without the need for an internet connection.

**Comment by matthew-brett** [comment]
I wonder whether wheels allow you to specify the binary platform - like `macosx-10.6-intel` but no particular version of Python?  As in something like `imageio-1.3-py2.py3-none-macosx-10.6-intel.whl` - with one wheel for each of OSX and Windows?   Then at least you could build and test the OSX and Windows wheels separately.

**Comment by almarklein** [comment]
@matthew-brett that would be convenient, but I've no idea if that's possible ...

**Comment by almarklein** [comment]
What's the status on this?

**Comment by blink1073** [comment]
I think it's waiting on me to finish MacPython/imageio-wheels.
I tried renaming the file, and it does not work:

```bash
$ pip install imageio-1.3-py2.py3-none-macosx_10_5_x86_64.whl
imageio-1.3-py2.py3-none-macosx_10_5_x86_64.whl is not a supported wheel on this platform.
```

**Comment by matthew-brett** [comment]
What do you get for `python -c "import distutils.util;
print(distutils.util.get_platform())"` ?

**Comment by blink1073** [comment]
macosx-10.5-x86_64

**Comment by matthew-brett** [comment]
Yes, I'm seeing the same thing - looks like you can't specify `py2.py3`
with the platform stuff.

I did get pip to use a wheel with suffix
`-cp27.cp33.cp34-none-macosx_10_6_intel.whl ` though (with my python.org
Python, on 2.7 and 3.3).

**Comment by blink1073** [comment]
Yep:

```bash
$ pip install imageio-1.3-cp27.cp34-none-macosx_10_5_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): imageio==1.3 from file:///Users/ssilvester/workspace/imageio/dist/imageio-1.3-cp27.cp34-none-macosx_10_5_x86_64.whl in /Users/ssilvester/anaconda/lib/python3.4/site-packages
```

**Comment by blink1073** [comment]
@almarklein, I switched to `python make test unit`, but I'm still seeing four errors: https://travis-ci.org/blink1073/imageio-wheels/builds/79024328.

The three failures in `test_avbin.py` are occurring locally on my machine as well.

**Comment by almarklein** [comment]
@blink1073 is that testing with a wheel or something? Not sure what to do with avbin. Maybe mark as known fails for now? Any idea why tempfile is imported? If it is expected, you can modify that test to ignore it.

**Comment by blink1073** [comment]
@almarklein, those tests were on my local install on OSX 10.10.5.

**Comment by almarklein** [comment]
But the Travis run, was it on imageio + modifications? I mean, so far Travis ran through the avbin tests ok. Any idea why not now?

**Comment by blink1073** [comment]
I assumed the MacPython builds were running on OSX, is that right @matthew-brett?

**Comment by matthew-brett** [comment]
Yes, right, they are running on an 10.9 OSX VM.

**Comment by almarklein** [comment]
Ah, I did not realize it was a Travis mac run. I say just disable avbin tests on OSX for now. It's interesting though, because the person who contributed tje avbin plugin is a mac user.

**Comment by blink1073** [comment]
I don't think skipping the tests is the right way to go, if the plugin can't read properly on OSX, it should at least indicate this to the user rather than failing because it can't read the metadata.

**Comment by almarklein** [comment]
So, are you suggesting to catch this error and raise using an exception with a more descriptive message?

**Comment by blink1073** [comment]
Yeah, I think that is a fair compromise.

**Comment by blink1073** [comment]
The problem is in the use of the alpha version of libavbin.  I downloaded ``libavbin.10.dylib` and the tests pass.

**Comment by blink1073** [comment]
@almarklein, would you accept a PR to this repo and imageio-binaries with version 10?

**Comment by almarklein** [comment]
I just did :)

**Comment by blink1073** [comment]
We now have http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/imageio-1.3-py2-none-any.whl, which should be valid as `imageio-1.3-cp27.cp33.cp34-none-macosx_10_5_x86_64.macosx_10_6_intel.whl`

**Comment by blink1073** [comment]
I verified that the wheel installs for me and functions correctly.

**Comment by blink1073** [comment]
Also works on python 3.5 if I add that to the name :smile:

**Comment by almarklein** [comment]
Sweet! How is it generated? Can we do t from imageio's setup.py?

**Comment by blink1073** [comment]
The wheel is generated by https://github.com/MacPython/imageio-wheels, we just need to update the submodule when we want to build a new version, then grab the wheel and rename it.

**Comment by almarklein** [comment]
and manually update that wheel to pypi?

**Comment by blink1073** [comment]
@matthew-brett, how do you deploy the OSX wheels for scikit-image?

**Comment by matthew-brett** [comment]
I used the `wheel-uploader` script - instructions e.g. here : https://github.com/MacPython/numpy-wheels#uploading-the-built-wheels-to-pypi

**Comment by blink1073** [comment]
Sounds reasonable, I'd need to update the file name in MacPython/imageio-wheels.

**Comment by blink1073** [comment]
Now available: http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/imageio-1.3-cp26.cp27.cp33.cp34.cp35-none-macosx_10_5_x86_64.macosx_10_6_intel.whl.

**Comment by almarklein** [comment]
Sweet! Does this mean the wheel-building is ready? Maybe we should document somewhere (in setup.py?) how we can build and deploy the wheels.

**Comment by blink1073** [comment]
IMHO, we should just use `setup.py` (with the latest commit), since we are not "compiling" for either platform every time.

**Pull request merged**
