### PR TITLE
FFMPEG_PATH can be specified by the user

### PR DESCRIPTION
**Pull request by Zulko**
Hi there ! I will try outsource all of MoviePy's video IO operations oh imageio. Some MoviePy users prefer to use their own FFMPEG binary instead of imageio's default. This commit gives a handle that I can use to easily change the path of the ffmpeg binary in imageio.

### CODE REVIEW

**Comment by almarklein** [comment]
What about using an environment variable? Seems a bit more flexible even.

**Comment by Zulko** [comment]
Maybe, I'm not really familiar with environment variables, what would be the advantage ? I have no objection to any solution that would allow me to change the settings during a python session.

**Comment by almarklein** [comment]
The advantage would be that users can set it also from outside the Python session, or without needing to import imageio first.

    # in plugins/ffmpeg.py
    ffmpeg_exe = os.getenv('IMAGEIO_FFMPEG_EXE')
    if ffmpeg_exe:
        return fmpeg_exe

    # Somewhere in the code:
    os.environ['IMAGEIO_FFMPEG_EXE'] = 'ffmpeg'

    # ... or at the command line:
    export IMAGEIO_FFMPEG_EXE=ffmpeg

**Comment by Zulko** [comment]
Ok, that would work for me.

**Comment by almarklein** [comment]
Just implemented this.

**Pull request closed without merging**
