### PR TITLE
Fix `SeekableFileObject` does not have `readline` when loading HTTP file

### LINKED ISSUE #1065: AttributeError: 'SeekableFileObject' object has no attribute 'readline'
trouble occur when reading some website address as follow, but same address is ok by skimage.io import imread:

  File "/usr/local/lib/python3.8/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/usr/local/lib/python3.8/site-packages/imageio/core/imopen.py", line 196, in imopen
    plugin_instance = candidate_plugin(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 104, in __init__
    with Image.open(request.get_file()):
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 3133, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 3119, in _open_core
    im = factory(fp, filename)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFile.py", line 116, in __init__
    self._open()
  File "/usr/local/lib/python3.8/site-packages/PIL/ImImagePlugin.py", line 153, in _open
    s = s + self.fp.readline()
AttributeError: 'SeekableFileObject' object has no attribute 'readline'

### PR DESCRIPTION
**Pull request by Pandede**
Fixes #1065.
The reason of this issue is `Pillow` sometimes read the image with `.readline` but not only `.read`.

**Update:**
It happens seldomly when loading a WebP image.

### CODE REVIEW

**Comment by Pandede** [comment]
I admit it is pretty weird about [this image](https://imagenes.20minutos.es/files/image_1920_1080/uploads/imagenes/2022/09/09/fotografia-a-coruna.jpeg): it has JPEG extension, but it is actually a WebP image.
However, when `Pillow` loads this image, it is recognized as an [IM image](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#im) and loads it with `Pillow.ImImagePlugin`, which requires the input file object supports `readline` (https://github.com/python-pillow/Pillow/blob/main/src/PIL/ImImagePlugin.py#L151).
Therefore, I may use the [IM testing image](https://github.com/python-pillow/Pillow/blob/main/Tests/images/hopper_long_name.im) of `Pillow`.

**Comment by Pandede** [comment]
I may reproduce the bug with [this test image](https://github.com/python-pillow/Pillow/raw/main/Tests/images/hopper_orientation_2.webp) of `Pillow`.
Note that although the extension of [this image](https://imagenes.20minutos.es/files/image_1920_1080/uploads/imagenes/2022/09/09/fotografia-a-coruna.jpeg) (fotografia-a-coruna.jpeg) is JPEG, it is actually a WebP image.

**Review by FirefoxMetzger — APPROVED** [review]
Pillow's test images work perfect for us :) LGTM

**Comment by Pandede** [comment]
It seems like `pillow` cannot to read WebP image as the missing package `libwebp-dev`.

**Comment by FirefoxMetzger** [comment]
Took a while to find the time to fix CI, but we eventually got there :) Thanks for the PR and thanks for being patient 🚀

**Pull request merged**
