### PR TITLE
DOC: Add an example for writing a video from raw numpy arrays with FFMPEG

### PR DESCRIPTION
**Pull request by hmaarrfk**
Awesome work guys!

It wasn't obvious to me that this was possible. I figured I would share.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
of course it was already there in the docs.

**Comment by hmaarrfk** [comment]
I guess the provided example does reading + writing, which was confusing as somebody new encoding videos.

**Comment by hmaarrfk** [comment]
Ok I reopened this PR but I changed the example to use vaapi.

My CPU stays cool while encoding!!!

**Comment by almarklein** [comment]
@hmaarrfk Thanks for all the work! I am a little busy right now, but I plan on having a look at your contributions/questions next week.

**Comment by hmaarrfk** [comment]
no problem, I know how these things go. It takes time and you might not want all of them.

**Comment by almarklein** [comment]
Nice example, thanks!

**Pull request merged**
