### PR TITLE
Proposed solution for issue 287 (prevent duplicate frames from webcam)

### PR DESCRIPTION
**Pull request by dennisvang**
Proposed solution for issue #287.

Adds a `_frame_is_new` attribute to the `FrameCatcher`, to indicate whether a returned frame is new.

The value of `_frame_is_new`  finally ends up in the `Image` meta dict, so it can be checked by a user if necessary, e.g:

```
image = reader.get_next_data()
if  image.meta['new']:
    update_stuff(image)

```

Also see implementation example in test.

### CODE REVIEW

**Comment by dennisvang** [comment]
Not sure what to do about these travis-ci failures...

**Comment by almarklein** [comment]
It seems that the latest flake8 has some new warnings:
```
Running flake8 on /home/travis/build/imageio/imageio
imageio/__main__.py:121:17: E722 do not use bare except'
imageio/plugins/_tifffile.py:3426:13: E741 ambiguous variable name 'l'
imageio/plugins/_tifffile.py:4052:13: E722 do not use bare except'
imageio/plugins/_tifffile.py:4563:5: E741 ambiguous variable name 'l'
tests/test_bin.py:41:5: E722 do not use bare except'
tests/test_ffmpeg.py:40:5: E722 do not use bare except'
```

If you don't mind, could you add E741 to the ignores here: https://github.com/imageio/imageio/blob/master/imageio/testing.py#L27, and turn the referenced lines from `except:` to `except Exception:`?

**Comment by almarklein** [comment]
The other CI fail seems like a glitch.

**Comment by dennisvang** [comment]
Sure. Done.

**Comment by almarklein** [comment]
I'm ignoring the glitch in the Python 2.6 build.

Thanks for this! Also happy to see unit tests. Is this ready from your end?

**Comment by dennisvang** [comment]
Yes, it is ready, as far as I can see. I've patched it into my current project and it seems to work well.

**Comment by almarklein** [comment]
Thanks!

**Comment by dennisvang** [comment]
My pleasure.

**Pull request merged**
