### PR TITLE
don't copy numpy memory when converting to PIL image.

### LINKED ISSUE #397: imageio writes grayscales uint8 bmp images slowly
What backend is imageio using for bmp images? I assumed it was pillow, but my benchmarks show me that something else is happening:

```
[ 75.00%] ··· benchmark_bmp.BMPSuite.time_load                                                                                                              ok
[ 75.00%] ··· ================ ============= ============ =============
              --                                 mode                  
              ---------------- ----------------------------------------
                   shape           redpil       pillow       imageio   
              ================ ============= ============ =============
                 (128, 128)      131±0.8μs     280±8μs       139±2μs   
                (1024, 1024)      199±3μs     753±200μs      196±6μs   
                (2048, 4096)    1.68±0.04ms   3.02±0.2ms   1.65±0.05ms 
               (32768, 32768)     355±10ms     229±4μs       370±20ms  
              ================ ============= ============ =============

[100.00%] ··· benchmark_bmp.BMPSuite.time_save                                                                                                              ok
[100.00%] ··· ================ ============ ============ ============
              --                                mode                 
              ---------------- --------------------------------------
                   shape          redpil       pillow      imageio   
              ================ ============ ============ ============
                 (128, 128)      100±7μs      255±20μs     372±30μs  
                (1024, 1024)    791±100μs    1.67±0.3ms   1.71±0.2ms 
                (2048, 4096)    4.72±0.2ms   5.25±0.1ms   12.6±0.9ms 
               (32768, 32768)    505±40ms     509±10ms    1.35±0.1s  
              ================ ============ ============ ============
```

Benchmarks taken from: https://github.com/hmaarrfk/redpil redpil still doesn't fully support bmp images, but the gap seems to be from a memory copy for file seek.

Seems suspicious that it is taking exactly 3 times as much time.

I can confirm that they all output files of the same size.

<details> <summary>Stub code to show that all files are of same size</summary>
Image can be found:  https://github.com/hmaarrfk/redpil/blob/master/tests/bmpsuite/g/pal8gs.bmp

```python
import imageio
a = imageio.imread('pal8gs.bmp')
import imageio
imageio.imwrite('test_imageio.bmp', a)
# from redpil.bmp import imwrite
# imwrite('test_redpil.bmp', a)

p = Image.fromarray(a)
p.save('pillow.bmp')
```
</details>

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes #397

### CODE REVIEW

**Comment by hmaarrfk** [comment]
It doesn't seem the style error isn't due to this.

**Comment by hmaarrfk** [comment]
@sciunto I think you may be interested in this. 2 large memory copies were definitely affecting the speed of writing images.

**Comment by almarklein** [comment]
Sorry it took a while to respond.

This looks great, thanks!

**Comment by hmaarrfk** [comment]
No problem. Glad to contribute back.

**Pull request merged**
