### PR TITLE
Add webm to list of supported ffmpeg formats

### PR DESCRIPTION
**Pull request by Skylion007**
FFMPEG has a webm muxer and can read and write to the format. We should support it so that we can read and write to the the format directly.

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
Seems like a good idea indeed. I will have a look at this after #595 is merged :)

**Comment by almarklein** [comment]
This looks good to me! Thanks!

**Comment by FirefoxMetzger** [comment]
I've added our CI pipeline to the PR.

**Comment by Skylion007** [comment]
@FirefoxMetzger Is this a false positive? I am not sure why adding this format would trigger an OS error

**Comment by Skylion007** [comment]
Yeah, tests are bit flaky. ;)

**Comment by Skylion007** [comment]
@almarklein @FirefoxMetzger awaiting merge.

**Comment by Skylion007** [comment]
Should I add a changelog entry?

**Comment by FirefoxMetzger** [comment]
@Skylion007 Yes that would be nice. Other than this, the PR looks good, and I will merge it towards the end of the week.

The CI pipeline breaking sporadically is not a good sign (it's new and shouldn't do that xD). I suspect that there may be a missing codec on windows that wasn't on one test runner but was available on the other. That's essentially why I didn't merge this already because I want to double-check that all the dependencies are tracked properly first. I'll have to dig into the logs to know this for sure though, which will happen after I completed setting up my new PC.

**Pull request merged**
