### PR TITLE
Add a reader plugin for the SPE format

### PR DESCRIPTION
**Pull request by lschr**
This PR adds a plugin which can read image files in the SPE format, including some of its metadata.

### CODE REVIEW

**Comment by lschr** [comment]
The necessary test image is subject to imageio/imageio-binaries#8.

**Comment by almarklein** [comment]
Thanks! This is already looking very good. I merged the test image and restarted Travis.

**Comment by almarklein** [comment]
This is ready, right?

**Comment by almarklein** [comment]
Hoozah, thanks!

**Pull request merged**
