### PR TITLE
Support HEIF image file

### PR DESCRIPTION
**Pull request by Pandede**
See #1021.
Read HEIF image with the elegant package [pillow_heif](https://github.com/bigcat88/pillow_heif) by @bigcat88 who comments in the issue.

### CODE REVIEW

**Comment by Pandede** [comment]
Sorry for the redundant commits as I forgot to update my forked repository first.

**Comment by bigcat88** [comment]
@Pandede you should not put it as an extra Pillow dependency.

It should be in ```extras_require`` or in ```plugins``` as a standalone record.

**Comment by Pandede** [comment]
> @Pandede you should not put it as an extra Pillow dependency.
> 
> It should be in `extras_require` or in `plugins` as a standalone record.

You mean the user should install the package via `pip install imageio[heif]`?
Could this make users think that plugins other than Pillow also support HEIF?

**Comment by bigcat88** [comment]
> 
> You mean the user should install the package via `pip install imageio[heif]`? Could this make users think that plugins other than Pillow also support HEIF?

Then just a usual way to just specify this as a separate entry in the plugins.

**Comment by Pandede** [comment]
I remake the pull request as the redundant commits.

**Pull request closed without merging**
