### PR TITLE
Bump tifffile to 2017.01.12

### PR DESCRIPTION
**Pull request by blink1073**
Bumps the python source to the latest version.

### CODE REVIEW

**Comment by blink1073** [comment]
Hmm, the original test correctly gets the `is_rgb` metadata for me locally but not on Travis.

**Comment by almarklein** [comment]
CI failed because of #231. Can you please rebase with master?

**Comment by blink1073** [comment]
Rebased, but still failing due the README: https://travis-ci.org/imageio/imageio/jobs/206569840

**Comment by almarklein** [comment]
Weird, I merged that PR to fix te numpy issue just this morning. Anyway, I fixed it (#233), please try again :)

**Comment by almarklein** [comment]
Looking good!

**Pull request merged**
