### PR TITLE
Update the `FfmpegFormat.Reader._terminate()` method to deal with webcam

### PR DESCRIPTION
**Pull request by dennisvang**
This should fix issue #343.

@almarklein Also added a rudimentary test for this issue. This test requires the `psutil` package, but I'm not sure where to specify this requirement (other than the `import` statement).

### CODE REVIEW

**Comment by dennisvang** [comment]
Added `psutil` to the Travis CI and AppVeyor yaml files so the CI checks pass. 

However, as the actual webcam tests are skipped during CI testing, I suppose it is still necessary to test this on different systems with a webcam in the loop.

**Comment by almarklein** [comment]
Thanks!

Great to have a specific test for this (even if it only runs locally when a webcam is present).

Do you know whether the not-terminating of ffmpeg is specific to webcam-mode? In other words, do you think that it can also apply to reading of video files with ffmpeg?

**Comment by dennisvang** [comment]
@almarklein The issue does not arise when I read a video file (on a windows 7 machine), e.g. using the example from the docs: [Iterate over frames in a movie](https://imageio.readthedocs.io/en/stable/examples.html#iterate-over-frames-in-a-movie)

**Comment by almarklein** [comment]
Thanks for this!

**Pull request merged**
