### PR TITLE
Fix issue 697: close standard streams properly, using sp.run

### PR DESCRIPTION
**Pull request by dennisvang**
This should fix issue #697.

The test has a temporary workaround, which could be removed after the acceptance of https://github.com/imageio/imageio-ffmpeg/pull/62 and subsequent release. Not sure how you would like to handle that.

### CODE REVIEW

**Comment by almarklein** [comment]
Is this an alternative for the fix in imageio-ffmpeg, or do they work in conjunction?

**Review by FirefoxMetzger — APPROVED** [review]
@dennisvang Thanks for this 🚀 Looking good from my end.

@almarklein Yes, the changes are in addition to the changes in `ffmpeg-imageio`, since we are leaking file handles in both places. Once when checking available cameras (handled here) and then later on when closing the camera resource (handled in ffmpeg-imageio).

**Review by almarklein — APPROVED** [review]

**Comment by FirefoxMetzger** [comment]
@dennisvang Could you merge this branch with the latest master (rebase also works depending on the workflow you prefer)? I fixed the pypy problem and a merge should allow the full matrix to run on the PR.

**Comment by dennisvang** [comment]
@FirefoxMetzger Sure, no problem.

Still failing on macos, I see. I guess the neatest solution would be to drop the [temporary part](https://github.com/imageio/imageio/pull/711/files#diff-e4e9cfdd4597c5c621ea46cab4445fbb747400f26b5c56c2a80fa0fe3cd1eeabR582) of that test.

Or just skip the assertion until the next release of `imageio_ffmpeg`, something like the following?

```python
def test_webcam_resource_warnings():
    try:
        with warns(None) as warnings:
            with imageio.get_reader("<video0>"):
                pass
    except IndexError:
        skip("no webcam")

    # todo: remove version check when imageio_ffmpeg issue #61 has been fixed
    import imageio_ffmpeg

    if tuple(int(v) for v in imageio_ffmpeg.__version__.split('.')) > (0, 4, 5):
        # there should be no warnings, but show warning messages if there are
        assert not [w.message for w in warnings]
```

**Comment by FirefoxMetzger** [comment]
@dennisvang Yeah, though we did progress by one step since we get to run the actual tests now instead of failing in the setup 😃 

The CPython MacOS tests pass fine, so I am surprised to see them fail on pypy. There is some difference in the memory management model though, so it could be that there is no leaking of `imageio-ffmpeg` on pypy?

There is also the failure on Windows in CPython that I haven't seen before. Not sure if this is a flakey test or if something happened. I will trigger a re-run of the CI and then we'll know more.

**Comment by FirefoxMetzger** [comment]
Okay, the windows tests still break with the same error messages; however #714 that was running through CI in parallel finished cleanly. This could be evidence that something is going wrong in this PR, but I don't have the time to dive into this right now. :(

Regarding the MacOS pypy test, I noticed that the linux builds all skip this test (because there is now webcam installed). The Windows and MacOS tests on the other hand run it but fail. I'm not sure if the GH Actions CI servers have webcams installed, so this could be an angle to investigate.

**Comment by dennisvang** [comment]
@FirefoxMetzger 

- Modified the `sp.run()` call to make it python 3.6 compatible. 
- Modified the *temporary* test so it allows "at most" one warning (from `imageio_ffmpeg`). 

I'm seeing all green now, except for the codecov/project check. Not sure what to do about that.

**Comment by FirefoxMetzger** [comment]
@dennisvang Thanks for that :) 

The codecov test is fine. We are removing a few lines that were covered before which slightly reduces the total number of lines in the project but keeps the number of uncovered lines the same. Thus, the coverage slightly decreases, but I don't mind that here.

**Comment by FirefoxMetzger** [comment]
@dennisvang I just went over the PR again, and it still looks good. Do you want to add anything more, or can I merge it?

**Comment by dennisvang** [comment]
@FirefoxMetzger That's great, thanks. :-) I have nothing more to add.

**Pull request merged**
