### PR TITLE
Mark gdal tests as requiring internet

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by almarklein** [comment]
CI fails now because of #231

**Comment by almarklein** [comment]
@ghisvail thanks for this patch. Can you please merge/rebase on master?

**Comment by ghisvail** [comment]
> Can you please merge/rebase on master?

Done

I saw quite a lot has happened in the last few months. Would you consider making another point release some time soon?

**Comment by almarklein** [comment]
Thanks! And I expect to find time to do a release this week or next.

**Comment by ghisvail** [comment]
> I expect to find time to do a release this week or next.

I was about to ask for it. Thanks.

**Comment by almarklein** [comment]
> And I expect to find time to do a release this week or next.

... or next :)

@ghisvail just released.

**Pull request merged**
