### PR TITLE
fix leaking file descriptor

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Comment by almarklein** [comment]
I've always understood that doing it this way closes the file right away. Are there cases where it does not?

**Comment by zshipko** [comment]
I'm not entirely sure. I just ran into a bunch of warnings about this last night when I was running some unit tests and figured I should just fix it -- at least, if nothing else, to avoid the errors while testing.

**Comment by almarklein** [comment]
Fair enough

**Comment by almarklein** [comment]
Thanks

**Pull request merged**
