### PR TITLE
BUG: avoid AttributeError when setting mode in Pillow v10.1

### PR DESCRIPTION
**Pull request by FirefoxMetzger**
Closes: #1044 

Pillow v10.1 removed the setter for `Image.mode` as this can have unintended consequences. This is done by making `Image.mode` a `@property` and keeping the mode in `Image._mode`. 

While okay in general, it breaks our setup as there is currently no good way of setting 16-bit return types directly (which we want when reading 16-bit grayscale PNGs). As a result, this change breaks our current setup. 

This PR introduces a "quick fix" by directly setting `Image._mode` instead of the previous `Image.mode`. I'm not fond of this solution, but until something better becomes available this is the only way I can think of to maintain our current behavior.

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
Looks like there is not just a problem with `Image.mode` becoming read-only, but also some additions to pillow's GIF reader that cause test failures.

I'll have to set some time aside to figure out where/why this breaks.

**Comment by lagru** [comment]
@FirefoxMetzger thanks for the quick reaction and working on this!

**Comment by lagru** [comment]
No worries. We've applied the same temporary fix to scikit-image and are in no particular hurry. Please don't feel rushed. :)

**Comment by FirefoxMetzger** [comment]
Looks like I finally managed to solve all the CI issues. Now it's only test coverage left. 

I also want to check why we can now use "rawmodes" like "I;16" in `PIL.Image.convert`, which wasn't possible before but is now. I need to double-check if this internally promotes to 32-bit or reads straight into 16-bit.

**Comment by FirefoxMetzger** [comment]
For future reference: Recent pillow versions no longer allow direct decoding of 16-bit grayscale PNGs. While we instruct Pillow to do so using the (now available) mode `I;16` in `Image.convert`, this will internally decode the image as 32-bit and then convert to 16-bit in a copy.

I will create a ticket over at pillow and see if we can bring the old functionality back since it is quite useful and I would eventually like to use it in other places as well.

**Pull request merged**
