### PR TITLE
add audio support for the writer

### PR DESCRIPTION
**Pull request by grovergol**
just forward the audio+path and audio_codec attributes to the write_frames method, so it's possible to include audio when using ffmpeg writer

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
Hej @grovergol , thanks for the contribution!

@almarklein You are the expert on the `imageio-ffmpeg` plugin. Does the backend support audio, or would the kwargs here fizzle? Also, I know you've been on the fence about the support for ffmpeg's filters that we added for the pyav plugin, so I would like to hear your thoughts on audio support (either reading or writing), for either imageio-ffmpeg or pyav.

**Comment by almarklein** [comment]
Yeah, I'm slightly reluctant because this is an image io library, but I can see the value ... besides, I've already been [lured](https://github.com/imageio/imageio-ffmpeg/pull/51) into adding these params to imageio-ffmpeg, so it would only be fair to accept it here as well :D

**Comment by almarklein** [comment]
Docs for this would be nice, but looks great other than that. Thanks!

**Comment by FirefoxMetzger** [comment]
Alright. In that case, I agree with @almarklein , we would need a mention of these parameters in the docs, here

https://github.com/imageio/imageio/blob/140707ae3c6eace7cf9131662197cc050d34cba3/imageio/plugins/ffmpeg.py#L57-L101

and if you can come up with a test that checks that there was actually some audio written to the file that would be good as well. It doesn't have to be a very sophisticated one, just something to make sure we don't accidentally break this functionality as we keep developing new things.

**Comment by FirefoxMetzger** [comment]
@grovergol I was wondering if you are still interested in working on this PR. It has been idle for close to a month now, and if you are no longer interested in working on this it would be good for us to know so other people may pick it up :)

**Comment by paulinevos** [comment]
Are you still looking for someone to pick this PR up?

**Comment by FirefoxMetzger** [comment]
@paulinevos Yes, we actually are. Would you be interested in picking it up and finishing it?

**Comment by FirefoxMetzger** [comment]
@paulinevos awesome! let me know if you need any help getting started.

**Comment by paulinevos** [comment]
@FirefoxMetzger @grovergol I don't have write access to the fork of course, would you like me to open a new PR and reference this one? I've finished it.

**Comment by paulinevos** [comment]
Opened a new PR finishing this one.

**Comment by FirefoxMetzger** [comment]
@paulinevos Exactly. You fork this PR branch and create a new PR against master :)

**Comment by FirefoxMetzger** [comment]
Superseeded by https://github.com/imageio/imageio/pull/882

**Pull request closed without merging**
