### PR TITLE
Fix bug of #1068 that `getattr` cannot get attribute with index directly

### PR DESCRIPTION
**Pull request by Pandede**
Small fix on PR #1068.
I think I should add the testcase to prove the PR works. Is that possible to expand the test image set?

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
@Pandede Yes, we can add more test images. However, the condition is that the image is CC0 licensed or that we get written permission to redistribute the image for testing purposes.

**Comment by Pandede** [comment]
Maybe I may use `requests` to download the dataset as temporary file for testing? This may avoid the license problem.

**Comment by Pandede** [comment]
Thanks for the comprehensive explanation! I would like to contact the author and ask for the write permission of the dataset.

**Comment by Pandede** [comment]
I have asked for the permission but it failed. I think this PR can be merged if you don't mind the missing of testcases.

**Comment by FirefoxMetzger** [comment]
Great, iirc the test image was the last piece missing in this PR :) Thank you for adding it @Pandede !

**Pull request merged**
