### PR TITLE
Fix GIF with P frame cannot be loaded 

### PR DESCRIPTION
**Pull request by Pandede**
See #1030

### CODE REVIEW

**Comment by Pandede** [comment]
The test case of ffmpeg is failed but I do not edit anything related to ffmpeg, may you check for the reason? Thank you!

**Comment by FirefoxMetzger** [comment]
Yes. This failure is related to the release of a new version of imageio-ffmpeg. I will have to look into this during the weekend and then fix it.

**Comment by FirefoxMetzger** [comment]
I fixed the `ffmpeg` error on master and merged it into this branch. Now CI should be happy :)

**Review by FirefoxMetzger — APPROVED** [review]
Nice changes @Pandede ! Sorry for being slow on the uptake on my side. 

I started a new job during the summer and I am still working out a routine of how to split my time between work, open source, and life so that each part gets the time it deserves 😅 .

**Pull request merged**
