### PR TITLE
Add ASCII format handling for PNM files

### LINKED ISSUE #445: PPM-FI not creating ASCII output
When ssing the PPM-FI format string, no ASCII output is created.

```python
imageio.imwrite(path, image_data, "PPM-FI")
```

Produces for example

```
P6
200 100
65535
<binary data>
```

This is the expected behavior when using PPMRAW-FI. The expected ASCII output would be something like 

```
P3
200 100
65535
1 2 3 4 5 6 ...
```

### PR DESCRIPTION
**Pull request by ttobsen**
Adding ASCII format support for PNM (Portable Anymap) files.

Fixes #445

### CODE REVIEW

**Comment by ttobsen** [comment]
I'v just added the PNM/PPM support and tested it localy with the following script:

```python
from imageio import imwrite, imread
import numpy as np
from binaryornot.check import is_binary

def is_ascii(file):
    is_bin = is_binary(file)
    return not is_bin

if __name__ == '__main__':

    tests = [
        {"data": np.full((200, 300, 3), 200, np.uint8),  "format": "PPM-FI",    "use_ascii": True},
        {"data": np.full((200, 300),    200, np.uint8),  "format": "PPM-FI",    "use_ascii": True},
        {"data": np.full((200, 300, 3), 200, np.uint8),  "format": "PPM-FI",    "use_ascii": False},
        {"data": np.full((200, 300),    200, np.uint8),  "format": "PPM-FI",    "use_ascii": False},
        {"data": np.full((200, 300, 3), 200, np.uint8),  "format": "PPMRAW-FI", "use_ascii": True},
        {"data": np.full((200, 300),    200, np.uint8),  "format": "PPMRAW-FI", "use_ascii": True},
        {"data": np.full((200, 300, 3), 200, np.uint8),  "format": "PPMRAW-FI", "use_ascii": False},
        {"data": np.full((200, 300),    200, np.uint8),  "format": "PPMRAW-FI", "use_ascii": False},
        {"data": np.full((200, 300, 3), 200, np.uint16), "format": "PPM-FI",    "use_ascii": True},
        {"data": np.full((200, 300),    200, np.uint16), "format": "PPM-FI",    "use_ascii": True},
        {"data": np.full((200, 300, 3), 200, np.uint16), "format": "PPM-FI",    "use_ascii": False},
        {"data": np.full((200, 300),    200, np.uint16), "format": "PPM-FI",    "use_ascii": False},
        {"data": np.full((200, 300, 3), 200, np.uint16), "format": "PPMRAW-FI", "use_ascii": True},
        {"data": np.full((200, 300),    200, np.uint16), "format": "PPMRAW-FI", "use_ascii": True},
        {"data": np.full((200, 300, 3), 200, np.uint16), "format": "PPMRAW-FI", "use_ascii": False},
        {"data": np.full((200, 300),    200, np.uint16), "format": "PPMRAW-FI", "use_ascii": False},
    ]

    for key, test in enumerate(tests):
        image_data = test["data"]
        filename = str(key) + ".ppm"
        fmt = test["format"]
        use_ascii = test["use_ascii"]

        imwrite(filename, image_data, fmt, use_ascii=use_ascii)
        assert is_ascii(filename) == use_ascii, "ASCII Flag missmatch!"
        read_data = imread(filename, fmt)

        np.testing.assert_array_equal(read_data, image_data, "Missmatch!")

        print("Test " + str(key) + " done.")
```

I'm not sure how to implement these tests properly. It seems that the special classes testing is done in `test_freeimage.py`. Are there any other places where tests have to be implemented?

As a starting point, I would use the Bitmap testing in `test_bmp()` as reference.

**Comment by almarklein** [comment]
>  Are there any other places where tests have to be implemented?

No, adding one test function to `test_freeimage.py` should be fine

**Comment by ttobsen** [comment]
> > Are there any other places where tests have to be implemented?
> 
> No, adding one test function to `test_freeimage.py` should be fine

Ok, I think I'm done. Can you have a look on it?

**Comment by almarklein** [comment]
This is great. No comments. Thanks for the contribution!

**Pull request merged**
