### PR TITLE
Allow JPEG quality factors > 95

### LINKED ISSUE #571: Saving high-quality JPEG ignores quality factor
After storing an image in JPEG format with imageio's imwrite method and quality 100, I was surprised to see that the quantization table of the saved image did not match my expectations, i.e., I would have expected a quantization table with all 1s. This is also the quantization table that Pillow produces for quality 100. The quantization tables also differ for quality factors 96 through 99.
Could someone please check whether I am using the imwrite method in the intended way? Otherwise, I think this might be a bug in imageio.

Here is the code to reproduce this issue:
```python
import imageio
import numpy as np
from PIL import Image
print(imageio.__version__)


# Create random pixels
img = np.random.randint(0, 256, size=(512, 512), dtype=np.uint8)
quality = 100

# Use imageio to save the image in JPEG format
imageio_filename = "/tmp/imageio.jpg"
imageio.imwrite(imageio_filename, img, quality=quality)

# Read quantization table from saved JPEG file
im = Image.open(imageio_filename)
quantization_table = np.array(im.quantization[0]).reshape(8, 8)
print("[imageio] Quantization table\n", quantization_table)

# Use Pillow to save the image
pil_filename = "/tmp/pil.jpg"
im = Image.fromarray(img)
im.save(pil_filename, quality=quality)

# Read quantization table from saved JPEG file
im = Image.open(pil_filename)
quantization_table = np.array(im.quantization[0]).reshape(8, 8)
print("[Pillow] Quantization table\n", quantization_table)
```

Output:
```
2.9.0
[imageio] Quantization table
 [[ 2  1  1  1  1  1  2  1]
 [ 1  1  2  2  2  2  2  4]
 [ 3  2  2  2  2  5  4  4]
 [ 3  4  6  5  6  6  6  5]
 [ 6  6  6  7  9  8  6  7]
 [ 9  7  6  6  8 11  8  9]
 [10 10 10 10 10  6  8 11]
 [12 11 10 12  9 10 10 10]]
[Pillow] Quantization table
 [[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
```

### PR DESCRIPTION
**Pull request by btlorch**
Removes the line that previously allowed a maximum JPEG quality factor of 95. Fixes #571.

### CODE REVIEW

**Comment by almarklein** [comment]
Thanks, that was quick :)    Could you please also update that (now invalid) comment just above?

**Comment by btlorch** [comment]
Sorry, I overlooked that comment earlier. According to the [Pillow docs](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg), the lowest possible quality factor is 0, so I would also allow a value of 0.
libjpeg doesn't recommend quality factors above 95, that's probably why imageio had quality factors > 95 disabled earlier. However, I believe this decision should be left to the user.

**Comment by almarklein** [comment]
Thanks for the fix!

**Comment by btlorch** [comment]
Thanks for pointing me towards the relevant lines!

**Pull request merged**
