### PR TITLE
Pillow plugin - the new default

### LINKED ISSUE #114: Alternatives for FreeImage
FreeImage is maintained by a small group of devs, which is not necessarily a bad thing, but they are on sourceforge with CVS for version control. On [people asking](http://sourceforge.net/p/freeimage/discussion/36111/thread/f2fae857/) them to move to Github, so they can have CI, more contributors, etc. they seem to fail to see the advantage.

This is slightly worrisome, and we should keep an eye out for alternatives, thus this issue.
- Nathanael Jones keeps a clone of freeimage. They have not changed code, but added CI: https://github.com/imazen/freeimage
- There's several other Freeimage clones on GH, but most seem to have changed the code.
- There is https://github.com/OpenImageIO/oiio
- We could ctypes into libjpeg and libpng (#111)
- Maybe  Luis' [imread](http://luispedro.org/software/imread/), which is C++, but maybe he can provide a C-api that we can talk to using ctypes.
- Pillow

### PR DESCRIPTION
**Pull request by almarklein**
This implements a plugin based on Pillow, to replace Freeimage.

Closes #114 
- [x] Allow a suffix in format names to specify the plugins, so that a format that is implemented by two plugins can still be distinguished.
- [x] Implement generic Pillow format for all singleton image formats.
- [x] Implement PNG format.
- [x] Implement JPEG format.
- [x] Implement GIF format based.
- [ ] Implement screen-grab format based on Pillow (#179)
- [x] Add pillow as a dependency.
- [x] Allow users to influence priority between plugins, #93.
- [x] Make freeimage an optional dependency
- [x] remove auto-download (#178)
- [x] Tests.
- [x] Check out https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_plugins/pil_plugin.py

### CODE REVIEW

**Comment by almarklein** [comment]
Almost done ...

**Comment by almarklein** [comment]
But my cycles for this week are spend. Probably wrap up + release next week.

**Comment by almarklein** [comment]
Time for merge; bye bye FreeImage, hello Pillow!

**Comment by blink1073** [comment]
:tada:

**Pull request merged**
