### PR TITLE
MAINT: Better Type Annotations + mypy support

### PR DESCRIPTION
**Pull request by FirefoxMetzger**
Closes: https://github.com/imageio/imageio/issues/763, https://github.com/imageio/imageio/issues/652, https://github.com/imageio/imageio/issues/651

This PR moves type annotations into dedicated `pyi` files and introduces a `ArrayLike` and a `ImageResource` type. 

The `ArrayLike` type is equal to `numpy.typing.ArrayLike` if numpy>=1.20 is installed, otherwise it falls back to `np.ndarray`. I think this should remove our dependency on numpy>1.20.

The `ImageResource` type is a convenience to indicate that the `uri` argument (which we should rename) can accept other types than strings.

### CODE REVIEW

**Comment by almarklein** [comment]
Wow. Out of curiosity, did you use a tool to generate these pyi files, or is that all manual work? 😲

**Comment by FirefoxMetzger** [comment]
So far I've done all of this manually. I move out the current type annotations into a pyi file and then I let mypy run over the library to statically validate the codebase and fix any problems that it finds.

I would like to be able to have all the `.pyi` files live in a separate folder/module, similar to header files in a C project. Unfortunately, I don't know if that is currently possible...

**Comment by FirefoxMetzger** [comment]
This PR is likely not perfect, but it accomplishes the main goals:

- remove the numpy>1.20 dependency
- enable mypy validation of files that use imageio
- move type annotations out of the main code and into pyi files for core files (I kept type annotations inside of plugins intact for now until we decide if they should be pulled out as well)

**Review by almarklein — APPROVED** [review]
I'm not going to check this line-by-line, but from a high level POV this looks good!

**Pull request merged**
