### PR TITLE
Fix #244: Issue using Pillow in a threaded context 

### LINKED ISSUE #244: Issue using Pillow in a threaded context
I'm reading a bunch of JPG files from multiple threads at the same time. I consistently get `"Imageio Pillow plugin requires Pillow lib."` from `imageio.plugins.pillow.PillowFormat._init_pillow()`. If I wrap everything inside `_init_pillow()` in a lock, it works fine. Any idea how to make sure that `_init_pillow()` was called without reading a fake JPG file?

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
On a side note, I suggest enabling "trim trailing whitespace" in your editor when editing .py files.

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
#244

**Comment by almarklein** [comment]
Thanks! A few style issues remain:
```
Running flake8 on /home/travis/build/imageio/imageio
imageio/plugins/pillow.py:35:80: E501 line too long (86 > 79 characters)
imageio/plugins/pillow.py:49:80: E501 line too long (81 > 79 characters)
imageio/plugins/pillow.py:53:80: E501 line too long (80 > 79 characters)
```

**Comment by NiklasRosenstein** [comment]
I hope I deducted the formatting correctly.

**Comment by almarklein** [comment]
Thanks!

**Pull request merged**
