### PR TITLE
Fix ffmpeg can_read for webcams with id greater than 10

### PR DESCRIPTION
**Pull request by hashb**
In our use case, we have over 20 webcams connected to a device at any given time. Currently only webcams up to id 9 are supported. This PR adds support for arbitrary number of cameras.

Please let me know if you want me to add any tests

### CODE REVIEW

**Review by FirefoxMetzger — CHANGES_REQUESTED** [review]
Thanks for this PR @hashb ! I agree that it makes a lot of sense to change to an implementation that isn't arbitrarily limited to a maximum number of video devics.

The PR itself looks pretty good. I would like to see one thing added here, which is a regression test at the bottom of `tests/test_ffmpeg.py` to make sure we don't accidentally undo this behavior later on. Can you add this, or should I do that?

**Comment by kchenna-nimble** [comment]
done. I have tested this only on linux but looks like it should work for other platforms too.

**Comment by hashb** [comment]
I have tested this only on linux but looks like it should work on other platforms too.

**Review by FirefoxMetzger — APPROVED** [review]
Nice work @hashb . I added two suggestions on the test, but otherwise I have nothing else to add.

If you agree with them, and the CI passes it is LGTM 🚀

**Comment by FirefoxMetzger** [comment]
Thanks for this contribution @hashb 🚀 The CD should release them tonight, so try upgrading imageio tomorrow and it should be fixed.

**Pull request merged**
