### PR TITLE
Fix test_video_format_to_dtype for d3d12

### PR DESCRIPTION
**Pull request by K900**
New video format added in recent ffmpeg releases, should be handled the same way as other hardware accelerated ones.

### CODE REVIEW

**Review by FirefoxMetzger — APPROVED** [review]
Open-and-shut case - LGTM

Thanks for the contribution! 🚀

**Comment by K900** [comment]
The test failure seems unrelated.

**Comment by K900** [comment]
So uh, how do I proceed here?

**Comment by K900** [comment]
I'm sorry if I'm being annoying, but can I get a merge here?

**Comment by FirefoxMetzger** [comment]
Sorry for being slow to respond. I was traveling for work this week. This tends to include "social activities" after work hours, so I end up with little time to spend on other stuff.

I could merge, but it will - unfortunately - just break again during CD later. The problem is that we need to deprecate python 3.8 support and tests. I was planning it for this weekend so we should be able to merge after that.

**Comment by K900** [comment]
Understood, thanks! We'll just vendor the patch in nixpkgs for now, then.

**Comment by FirefoxMetzger** [comment]
I encountered this one while removing 3.8 support. 😅 

I will merge and then rebase my PR on yours. Thanks for the contribution :)

**Pull request merged**
