### PR TITLE
Allow saving tiff resolution unit.

### LINKED ISSUE #142: resolution_unit tag for TIFF format
This is a small enhancement request for the TIFF format writer: support writing the resolution unit metadata entry (which can be inches (the current default) or cm, see http://www.awaresystems.be/imaging/tiff/tifftags/resolutionunit.html).

### PR DESCRIPTION
**Pull request by anntzer**
Fixes #142.

### CODE REVIEW

**Comment by almarklein** [comment]
I think a change like that should be contributed to the tiffille project, since we're basically vendoring that. A change done to the file here will be undone when we update tiffile.

Correct me if I'm wrong @blink1073

**Comment by anntzer** [comment]
Well, I noticed that C. Gohlke recently implemented the same thing, so just updating it would work too :-) (http://www.lfd.uci.edu/~gohlke/code/tifffile.py.html see 2016-05-13 entry).

**Comment by blink1073** [comment]
I'd say it is fine to merge this here, I'll update tifffile as well.

**Comment by almarklein** [comment]
Tests fails are spurious. Let's merge then.

**Pull request merged**
